# Generated by Django 3.0.4 on 2020-04-10 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlTypeMaster',
            fields=[
                ('ControlID', models.AutoField(primary_key=True, serialize=False)),
                ('ControlName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ControlMaster',
            },
        ),
        migrations.CreateModel(
            name='IssueOriginMaster',
            fields=[
                ('IssOriID', models.AutoField(primary_key=True, serialize=False)),
                ('IssOriName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'IssueOriginMaster',
            },
        ),
        migrations.CreateModel(
            name='ProblemMaster',
            fields=[
                ('ProblemID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('ProblemTitle', models.CharField(max_length=250)),
                ('ProblemDesc', models.CharField(max_length=1000)),
                ('CreatedDate', models.DateTimeField(auto_now=True)),
                ('UpdatedDate', models.DateTimeField(auto_now=True)),
                ('Isactive', models.BooleanField(default=True)),
                ('ControlID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gyankosh_API.ControlTypeMaster')),
            ],
            options={
                'db_table': 'ProblemMaster',
            },
        ),
        migrations.CreateModel(
            name='TechnologyMaster',
            fields=[
                ('TechID', models.AutoField(primary_key=True, serialize=False)),
                ('TechName', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'TechnologyMaster',
            },
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=30)),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=255)),
                ('Isactive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'UserMaster',
            },
        ),
        migrations.CreateModel(
            name='SolutionMaster',
            fields=[
                ('SolutionID', models.AutoField(primary_key=True, serialize=False)),
                ('IsVerified', models.BooleanField(default=False)),
                ('SolutionDesc', models.CharField(max_length=1000)),
                ('CreatedDate', models.DateTimeField(auto_now=True)),
                ('UpdatedDate', models.DateTimeField(auto_now=True)),
                ('Isactive', models.BooleanField(default=True)),
                ('ProblemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gyankosh_API.ProblemMaster')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gyankosh_API.UserMaster')),
            ],
            options={
                'db_table': 'SolutionMaster',
            },
        ),
        migrations.AddField(
            model_name='problemmaster',
            name='TechID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gyankosh_API.TechnologyMaster'),
        ),
        migrations.AddField(
            model_name='problemmaster',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gyankosh_API.UserMaster'),
        ),
        migrations.AddField(
            model_name='controltypemaster',
            name='TechID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gyankosh_API.TechnologyMaster'),
        ),
    ]
