# Generated by Django 3.0.4 on 2020-04-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gyankosh_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controltypemaster',
            name='ControlID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='issueoriginmaster',
            name='IssOriID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='problemmaster',
            name='ProblemID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solutionmaster',
            name='SolutionID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='technologymaster',
            name='TechID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='UserID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
