# Generated by Django 3.0.4 on 2020-04-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gyankosh_API', '0002_auto_20200410_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='UserName',
            field=models.CharField(max_length=50),
        ),
    ]
